name: service_hub_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.4.1
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.1
  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.9.0
  geolocator: ^9.0.0
  geocoding: ^2.0.5
  get: ^4.6.6
  get_storage: ^2.1.1
  flutter_svg: ^2.0.10+1
  shared_preferences: ^2.3.2
  flutter_screenutil: ^5.9.3
  percent_indicator: ^4.2.3
  country_pickers: ^3.0.1
  intl_phone_field: ^3.2.0
  flutter_otp_text_field: ^1.2.0
  flutter_clean_calendar: ^1.1.0
  table_calendar: ^3.0.3
  bottom_sheet: ^4.0.4
  expandable_text: ^2.3.0
  html_editor_enhanced: ^2.6.0
  flutter_time_picker_spinner: ^2.0.0
  fluttertoast: ^8.2.8
  flutter_staggered_animations: ^1.1.1
  intl: ^0.17.0
  image_picker: ^0.8.5
  flutter_pytorch: ^1.0.1
  url_launcher: ^6.1.7 # Use the latest version from pub.dev



dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  assets:
    - assets/
  fonts:
    - family: Schyler
      fonts:
        - asset: fonts/Inter-Bold.ttf
          weight: 700
        - asset: fonts/Inter-Regular.ttf
          weight: 500
        - asset: fonts/Inter-Regular.ttf
          weight: 400
        - asset: fonts/Inter-Medium.ttf
          weight: 600
        - asset: fonts/Inter-ExtraBold.ttf
          weight: 800
    - family: CircularStd
      fonts:
        - asset: fonts/CircularStd-Bold.ttf
          weight: 700
        - asset: fonts/CircularStd-Medium.otf
          weight: 500
        - asset: fonts/FontsFree-Net-Circular-Std-Book.ttf
          weight: 400
    - family: Gilroy
      fonts:
        - asset: fonts/Gilroy-Bold.ttf
          weight: 700
        - asset: fonts/Gilroy-Medium.ttf
          weight: 500
        - asset: fonts/Gilroy-Regular.ttf
          weight: 400
